#!/bin/bash
# Rebuilds the combined question bank from the per-topic files in topics/.
# Run this after editing any topic file, then commit both.
#
#   bash build_bank.sh
#
set -e
cd "$(dirname "$0")"
OUT=oop_self_assessment_mcq.gift

bash validate_gift.sh topics/*.gift

{
  echo '// ============================================================'
  echo '// COMP C8Z03 - Year 2 OOP: Self-Assessment Quiz (all topics)'
  echo '// ============================================================'
  echo '// Format    : Moodle GIFT'
  echo '// GENERATED : do not edit this file by hand.'
  echo '//             Edit the per-topic files in topics/ and re-run'
  echo '//             build_bank.sh, which also validates them.'
  echo "// Topics    : $(ls topics/*.gift | wc -l | tr -d ' ')"
  echo "// Questions : $(cat topics/*.gift | grep -c '^::')"
  echo '// ------------------------------------------------------------'
  echo '// HOW TO IMPORT INTO MOODLE:'
  echo '//   1. Course > Question bank > Import'
  echo '//   2. Choose file format "GIFT format"'
  echo '//   3. Upload this file (or a single topic file for one week)'
  echo '//   4. Questions are filed under the $CATEGORY tags below'
  echo '// ============================================================'
  echo
  for f in $(ls topics/*.gift | sort); do
    # skip each topic file's own banner, keep its $CATEGORY line onwards
    sed -n '/^\$CATEGORY/,$p' "$f"
    echo
  done
} > "$OUT"

echo "Wrote $OUT ($(grep -c '^::' "$OUT") questions, $(grep -c '^\$CATEGORY' "$OUT") categories)"
